// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {frontscan} from '../models';
import {relayvpn} from '../models';

export function GetConfig():Promise<config.Config>;

export function InstallCA():Promise<void>;

export function IsCATrusted():Promise<boolean>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function ScanFrontIPs():Promise<Array<frontscan.Result>>;

export function Start():Promise<void>;

export function Stats():Promise<relayvpn.Stats>;

export function Status():Promise<relayvpn.Status>;

export function Stop():Promise<void>;

export function ToggleAccount(arg1:string,arg2:boolean):Promise<void>;

export function UninstallCA():Promise<void>;

export function ValidateConfig(arg1:config.Config):Promise<void>;
