// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateAuthKey() {
  return window['go']['main']['App']['GenerateAuthKey']();
}

export function GetCACertInfo() {
  return window['go']['main']['App']['GetCACertInfo']();
}

export function GetCodeGS() {
  return window['go']['main']['App']['GetCodeGS']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function InstallCA() {
  return window['go']['main']['App']['InstallCA']();
}

export function IsCATrusted() {
  return window['go']['main']['App']['IsCATrusted']();
}

export function IsSetupCompleted() {
  return window['go']['main']['App']['IsSetupCompleted']();
}

export function MarkSetupCompleted() {
  return window['go']['main']['App']['MarkSetupCompleted']();
}

export function RevealCACert() {
  return window['go']['main']['App']['RevealCACert']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function ScanFrontIPs() {
  return window['go']['main']['App']['ScanFrontIPs']();
}

export function Start() {
  return window['go']['main']['App']['Start']();
}

export function Stats() {
  return window['go']['main']['App']['Stats']();
}

export function Status() {
  return window['go']['main']['App']['Status']();
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}

export function ToggleAccount(arg1, arg2) {
  return window['go']['main']['App']['ToggleAccount'](arg1, arg2);
}

export function UninstallCA() {
  return window['go']['main']['App']['UninstallCA']();
}

export function ValidateConfig(arg1) {
  return window['go']['main']['App']['ValidateConfig'](arg1);
}
